### ISSUE TITLE
Prune the number of database and asset backups stored

### ISSUE THREAD

**Issue by zizther** [weareferal/craft-sync#11]
When pushing a backup on the database or assets, does it remove the old version does before adding the new one, or does it keep adding them indefinitely to the storage location?

If it doesn't already, a nice feature would be to prune the number backups stored via a settings, blank would mean indefinite number, else it would remove the occurrences over the value set.

I know this may not be necessary for everyone, and in most cases not an issues with the cost of services like S3.

**Comment by timmyomahony** [comment]
@zizther it doesn't currently but that's a good idea. I hadn't thought of simply keeping a "number of backups" setting. One way of doing that might be a couple of different settings:

- X yearly backup
- X monthly backups
- X weekly backups
- X daily backup

Or something like that. It would either need to happen when you create a new backup, periodically or simply with the push of a button.

**Comment by zizther** [comment]
Yeah, that makes sense, there is definitely a couple of ways to approach it and I am sure different users will have different requirements, but the example you set seems pretty good.

**Comment by timmyomahony** [comment]
I've added this in v1.1.0
