### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by zizther** [weareferal/craft-sync#12]
Not that this plugin isn't easy to use already, a good feature would be to add in console commands to push and pull.

Depending on how you have it setup, an example could be.

`./craft envsync/assets/push`
`./craft envsync/assets/pull`

`./craft envsync/db/push`
`./craft envsync/assets/pull`

This would allow for use outside the CP, which could tie into a CI/CD process, or for those who love the command line.

With this in mind, it could be useful for this plugin to have its own config file, which would still use the env vars to setup, if needed, then the plugin would auto populate if this config file was used, this could help keep things managed outside the CP too.

**Comment by timmyomahony** [comment]
Hey. These actually exists:

https://github.com/weareferal/craft-env-sync/tree/master/src/console/controllers

but for some reason aren't showing up when I test myself so I'll look at that now. They're also not mentioned in the README so I'll also add that.

Regarding the config file, good idea. I can add an example config file as well as some feedback in the settings page if they're overwritten by the config.

**Comment by timmyomahony** [comment]
They should be available as:

```
- env-sync/database                         Sync database backups
    env-sync/database/create-backup         Create a local database backup
    env-sync/database/pull                  Pull remote database backups from cloud
    env-sync/database/push                  Push local database backups to cloud

- env-sync/volumes                          Sync volumes backup
    env-sync/volumes/create-backup          Create a local volumes backup
    env-sync/volumes/pull                   Pull remote volume backups from cloud
    env-sync/volumes/push                   Push local volume backups to cloud
```

e.g.

```
> ./craft env-sync/volumes/create-backup
```

**Comment by timmyomahony** [comment]
Added to the docs now https://github.com/weareferal/craft-env-sync#command-line so should be working correctly

**Comment by zizther** [comment]
Amazing man, real handy!
